# Generated by Django 3.2.6 on 2021-08-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
